-- Home Logistics Supabase schema
-- Run this in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_empty check (length(trim(name)) > 0),
  constraint categories_user_name_unique unique (user_id, name)
);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  category text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stores_name_not_empty check (length(trim(name)) > 0),
  constraint stores_category_not_empty check (length(trim(category)) > 0),
  constraint stores_user_name_category_unique unique (user_id, name, category)
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  brand text,
  category text not null,
  quantity integer not null default 0,
  minimum_quantity integer not null default 0,
  unit text not null default 'pz',
  preferred_store_id bigint references public.stores(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_items_name_not_empty check (length(trim(name)) > 0),
  constraint inventory_items_category_not_empty check (length(trim(category)) > 0),
  constraint inventory_items_quantity_non_negative check (quantity >= 0),
  constraint inventory_items_minimum_non_negative check (minimum_quantity >= 0),
  constraint inventory_items_unit_not_empty check (length(trim(unit)) > 0)
);

create table if not exists public.shopping_list_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  category text not null,
  is_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shopping_entries_name_not_empty check (length(trim(name)) > 0),
  constraint shopping_entries_category_not_empty check (length(trim(category)) > 0)
);

create table if not exists public.shopping_entry_stores (
  entry_id bigint not null references public.shopping_list_entries(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (entry_id, store_id)
);

create table if not exists public.home_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  notes text,
  recurrence_days integer,
  next_due_date date not null,
  is_completed boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_tasks_title_not_empty check (length(trim(title)) > 0),
  constraint home_tasks_recurrence_positive check (
    recurrence_days is null or recurrence_days > 0
  )
);

create table if not exists public.home_task_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  task_id bigint not null references public.home_tasks(id) on delete cascade,
  task_title text not null,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint home_task_completions_title_not_empty check (length(trim(task_title)) > 0)
);

create index if not exists categories_user_id_idx on public.categories(user_id);
create index if not exists stores_user_id_idx on public.stores(user_id);
create index if not exists stores_user_category_idx on public.stores(user_id, category);
create index if not exists inventory_items_user_id_idx on public.inventory_items(user_id);
create index if not exists inventory_items_user_category_idx on public.inventory_items(user_id, category);
create index if not exists shopping_entries_user_id_idx on public.shopping_list_entries(user_id);
create index if not exists shopping_entries_user_completed_idx on public.shopping_list_entries(user_id, is_completed);
create index if not exists shopping_entry_stores_user_id_idx on public.shopping_entry_stores(user_id);
create index if not exists home_tasks_user_due_idx on public.home_tasks(user_id, next_due_date);
create index if not exists home_tasks_user_active_idx on public.home_tasks(user_id, is_active, is_completed);
create index if not exists home_task_completions_user_completed_idx on public.home_task_completions(user_id, completed_at desc);

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists stores_set_updated_at on public.stores;
create trigger stores_set_updated_at
before update on public.stores
for each row execute function public.set_updated_at();

drop trigger if exists inventory_items_set_updated_at on public.inventory_items;
create trigger inventory_items_set_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

drop trigger if exists shopping_entries_set_updated_at on public.shopping_list_entries;
create trigger shopping_entries_set_updated_at
before update on public.shopping_list_entries
for each row execute function public.set_updated_at();

drop trigger if exists home_tasks_set_updated_at on public.home_tasks;
create trigger home_tasks_set_updated_at
before update on public.home_tasks
for each row execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.stores enable row level security;
alter table public.inventory_items enable row level security;
alter table public.shopping_list_entries enable row level security;
alter table public.shopping_entry_stores enable row level security;
alter table public.home_tasks enable row level security;
alter table public.home_task_completions enable row level security;

drop policy if exists "categories_select_own" on public.categories;
create policy "categories_select_own"
on public.categories for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "categories_insert_own" on public.categories;
create policy "categories_insert_own"
on public.categories for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "categories_update_own" on public.categories;
create policy "categories_update_own"
on public.categories for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "categories_delete_own" on public.categories;
create policy "categories_delete_own"
on public.categories for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "stores_select_own" on public.stores;
create policy "stores_select_own"
on public.stores for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "stores_insert_own" on public.stores;
create policy "stores_insert_own"
on public.stores for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "stores_update_own" on public.stores;
create policy "stores_update_own"
on public.stores for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "stores_delete_own" on public.stores;
create policy "stores_delete_own"
on public.stores for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "inventory_items_select_own" on public.inventory_items;
create policy "inventory_items_select_own"
on public.inventory_items for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "inventory_items_insert_own" on public.inventory_items;
create policy "inventory_items_insert_own"
on public.inventory_items for insert
to authenticated
with check (
  auth.uid() = user_id
  and (
    preferred_store_id is null
    or exists (
      select 1 from public.stores s
      where s.id = preferred_store_id and s.user_id = auth.uid()
    )
  )
);

drop policy if exists "inventory_items_update_own" on public.inventory_items;
create policy "inventory_items_update_own"
on public.inventory_items for update
to authenticated
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and (
    preferred_store_id is null
    or exists (
      select 1 from public.stores s
      where s.id = preferred_store_id and s.user_id = auth.uid()
    )
  )
);

drop policy if exists "inventory_items_delete_own" on public.inventory_items;
create policy "inventory_items_delete_own"
on public.inventory_items for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "shopping_entries_select_own" on public.shopping_list_entries;
create policy "shopping_entries_select_own"
on public.shopping_list_entries for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "shopping_entries_insert_own" on public.shopping_list_entries;
create policy "shopping_entries_insert_own"
on public.shopping_list_entries for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "shopping_entries_update_own" on public.shopping_list_entries;
create policy "shopping_entries_update_own"
on public.shopping_list_entries for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "shopping_entries_delete_own" on public.shopping_list_entries;
create policy "shopping_entries_delete_own"
on public.shopping_list_entries for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "shopping_entry_stores_select_own" on public.shopping_entry_stores;
create policy "shopping_entry_stores_select_own"
on public.shopping_entry_stores for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "shopping_entry_stores_insert_own" on public.shopping_entry_stores;
create policy "shopping_entry_stores_insert_own"
on public.shopping_entry_stores for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.shopping_list_entries e
    where e.id = entry_id and e.user_id = auth.uid()
  )
  and exists (
    select 1 from public.stores s
    where s.id = store_id and s.user_id = auth.uid()
  )
);

drop policy if exists "shopping_entry_stores_delete_own" on public.shopping_entry_stores;
create policy "shopping_entry_stores_delete_own"
on public.shopping_entry_stores for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "home_tasks_select_own" on public.home_tasks;
create policy "home_tasks_select_own"
on public.home_tasks for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "home_tasks_insert_own" on public.home_tasks;
create policy "home_tasks_insert_own"
on public.home_tasks for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "home_tasks_update_own" on public.home_tasks;
create policy "home_tasks_update_own"
on public.home_tasks for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "home_tasks_delete_own" on public.home_tasks;
create policy "home_tasks_delete_own"
on public.home_tasks for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "home_task_completions_select_own" on public.home_task_completions;
create policy "home_task_completions_select_own"
on public.home_task_completions for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "home_task_completions_insert_own" on public.home_task_completions;
create policy "home_task_completions_insert_own"
on public.home_task_completions for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.home_tasks t
    where t.id = task_id and t.user_id = auth.uid()
  )
);
